### ISSUE TITLE
Final source checklist for Hack v3.0 UFO conversion

### ISSUE THREAD

**Issue by chrissimpkins** [sf-playground/ufo-curves#4]
- used branch: `FLS_UFO_2_glyphs_UFO` (FLS VI PS curve UFO, re-exported with Glyphs) as base
- branched to the branch `final_source`

- [X] modified fontinfo.plist files in Hack-Regular.ufo, Hack-Bold.ufo, Hack-Italic.ufo, Hack-BoldItalic.ufo with updated data and corrections for incorrect data
- [X] proof cubic/quadratic curves in UFO source
- [X] proof renders directly from UFO source
- [X] test build of ttf fonts with fontmake
- [x] proof shapes of ASCII characters in ttf files built with new source files + fontmake compiler
- [x] proof OpenType table contents in ttf files built with new source files + fontmake compiler
- [x] proof hinted ttf files (ttfautohint) to confirm that instruction set changes are not required c/w previous builds
- [x] FontBakery testing on ttf files built with new source files + fontmake compiler

**Comment by chrissimpkins** [comment]
New `fontmake` ttf builds (unhinted) are now available in https://github.com/sf-playground/ufo-curves/tree/final_source/source/ufo/master_ttf and ready for testing. 

Required some minor modifications of the UFO source to complete the build process.  These changes were to values in the OT tables only (styleName and postscriptBlueValues in fontinfo.plist files - former issue was improper binary naming, latter issue was exception raised on build attempt for Bold and BoldItalic variants).  There were no modifications to .glif files. 

 Current source in `final_source` branch is the set of source that I used for the build.

**Comment by chrissimpkins** [comment]
I can verify that the OS X testing available in FontBook shows that all OT tables are valid on the OS X platform.

I will be diffing the OT tables in the binaries this week.

**Comment by burodepeper** [comment]
Below the screenshots (click for full size) of the full ascii table generated at 256px with my visual-diff tool, based on the UFO source. Some punctuation, such as `{` and `}` is not rendered in its entirety, because they are drawn outside of the glyph box.

**Summary:** I have not spotted any unexpected rendering.

![schermafbeelding 2017-07-17 om 07 33 01](https://user-images.githubusercontent.com/3703530/28256434-d8ebc104-6ac2-11e7-81ba-b27df8723841.png)
![schermafbeelding 2017-07-17 om 07 34 14](https://user-images.githubusercontent.com/3703530/28256436-dd29999e-6ac2-11e7-9bd0-e339f95a9ac1.png)
![schermafbeelding 2017-07-17 om 07 35 15](https://user-images.githubusercontent.com/3703530/28256438-de885f8c-6ac2-11e7-9e3c-ad4a46888130.png)
![schermafbeelding 2017-07-17 om 07 35 52](https://user-images.githubusercontent.com/3703530/28256441-e012efc0-6ac2-11e7-92a7-faa89cd59ee8.png)
![schermafbeelding 2017-07-17 om 07 36 20](https://user-images.githubusercontent.com/3703530/28256442-e1918c8a-6ac2-11e7-81f9-df46fb0a135a.png)
![schermafbeelding 2017-07-17 om 07 36 40](https://user-images.githubusercontent.com/3703530/28256443-e3043586-6ac2-11e7-9d47-4e35f96f1181.png)
![schermafbeelding 2017-07-17 om 07 37 06](https://user-images.githubusercontent.com/3703530/28256444-e4772752-6ac2-11e7-82ef-00f49ee28ed0.png)

**Comment by burodepeper** [comment]
I have manually looked at the UFO source of the following handpicked semi-random glyphs:

- J_.glif
- K_.glif
- Q_.glif
- R_.glif
- braceright.glif
- asciitilde.glif
- e.glif
- i.glif
- t.glif
- u.glif
- dollar.glif
- ampersand.glif
- two.glif
- semicolon.glif

They all look 'healthy' to me.

I will render a subset of the renders above comparing the other three variants.

**Comment by burodepeper** [comment]
Again, no visual inconsistencies, as far as I can see.

![schermafbeelding 2017-07-17 om 07 54 33](https://user-images.githubusercontent.com/3703530/28256767-ad78cfbe-6ac5-11e7-831e-3c560aa69c09.png)
![schermafbeelding 2017-07-17 om 07 55 48](https://user-images.githubusercontent.com/3703530/28256768-af3397e4-6ac5-11e7-83a0-d92ff63dd416.png)
![schermafbeelding 2017-07-17 om 07 56 19](https://user-images.githubusercontent.com/3703530/28256770-b1553c76-6ac5-11e7-93ca-ad01a6332dde.png)
![schermafbeelding 2017-07-17 om 07 57 51](https://user-images.githubusercontent.com/3703530/28256771-b3395fd6-6ac5-11e7-8824-c8c2af396268.png)

**Comment by chrissimpkins** [comment]
Thanks David.  That's great news.  To confirm, all of the above were rendered directly from UFO source files and none were rendered from the ttf builds?

**Comment by burodepeper** [comment]
> To confirm, all of the above were rendered directly from UFO source files and none were rendered from the ttf builds?

Yes. You can download the visual-diff tool and verify it, if you have nothing better to do.

**Comment by chrissimpkins** [comment]
OK thanks.  That is useful.  We know that the design is consistent at this point and that there were no significant errors in the source conversion for the tested files. 

Will try to come up with an approach to look at the ttf builds in order to confirm that the new build process is not leading to problems.  We have introduced a new curve conversion tool (with associated defaults in integrity of conversion) and new compiler in the mix.  Might be able to simply open the ttf files in a font editor and examine sets.

**Comment by burodepeper** [comment]
Use my renders as reference images in your editor?

**Comment by chrissimpkins** [comment]
way to overlay/underlay these?

**Comment by burodepeper** [comment]
Should be a feature in your editor. In Glyphs you can choose an image as reference, and draw your shapes on top of it. I'm sure FLS has something similar. Just drag the images into your editor, and see what happens.

**Comment by chrissimpkins** [comment]
I have Glyphs.  Let me see if I can get it to work.  Thanks David.

**Comment by chrissimpkins** [comment]
OT tables are good.  Clear to use this source

**Comment by chrissimpkins** [comment]
Shapes across the four variant sets are good based upon proof of ASCII glyphs. Found this tool: 

http://www.fonttools.org/downloads/OTMA/OTM_Light_370_MAC.zip

that shows side by side glyph presentation for different builds.  Not perfect but better than nothing at this stage.

![side-by-side](https://user-images.githubusercontent.com/4249591/28295218-2631dc2c-6b2d-11e7-90e6-9d117dab45bf.png)

**Comment by chrissimpkins** [comment]
Hints look pretty good overall for the regular set.  Few things that we will need to address.  Changed some settings and I think that we are getting better overall hinting at small sizes for the lowercase alphabetic glyphs.  Zero will need a bit of touchup:

![2017-07-20 22 34 58](https://user-images.githubusercontent.com/4249591/28446969-a0fd8e5a-6dbd-11e7-9bf4-40a0a4a7f839.gif)

High priority manual hinting needs in regular:

- `#` @ 8, 13
- `%` @ 7, 10, 14
- `+` @ 7, 12, 13
- `0` @ 7, 8, 12, 13, 14

**Comment by chrissimpkins** [comment]
Will check bold, italic, and bold italic sets this weekend.

**Comment by chrissimpkins** [comment]
Italic set good overall.  

High priority manual hinting needs in italic set:

- `%` @ 10

**Comment by chrissimpkins** [comment]
High priority manual hinting needs in bold set:

- `!` @ 14
- `%` @ 10, 11
- `+` @ 10, 11, 15
- `5` @ 9
- `8` @ 12, 13, 14

**Comment by burodepeper** [comment]
Is that part of "Final source checklist for Hack v3.0 UFO conversion" or is it a separate issue?

**Comment by chrissimpkins** [comment]
Just maintaining the hint needs for new issue reports.  Will move the source as soon as I confirm that there are no serious problems with any ascii glyphs and run the font bakery tests to make sure that we don't need any other OT modifications.  So far across sizes 6-15 for ascii glyphs things look pretty good.  One set to go.  Will complete all of this over the weekend.

**Comment by chrissimpkins** [comment]
High priority manual hinting needs in bold italic set:

- `+` @ 10, 11, 15

Otherwise look good.

**Comment by chrissimpkins** [comment]
Hints checked from 6 - 15ppem across all variants.  Will proof fonts with Font Bakery tomorrow to confirm that there are no tweaks to the source that are necessary, then will plan to shift the source over to the Hack repository before the transition here.  Build to desktops is implemented and will put the shell scripts together and complete remainder of build toolchain work there.  

Will plan to add the above hinting issues as new issue reports on the repository and will address all of these for the first v3.0 release.  Will need to discuss whether there are plans to modify any of the affected glyphs before I dig into manual hinting.

**Comment by chrissimpkins** [comment]
Finished fontbakery checks.  

Adding dsig table fix to post ttf build script.

Adding fstype reset to value of 0 fix to post ttf build script

**Comment by chrissimpkins** [comment]
Source ready to be imported into Hack repository

**Comment by chrissimpkins** [comment]
New source is now available in master branch of Hack repository.

**Comment by chrissimpkins** [comment]
Will add the hinting needs as new IR's on the Hack repository.  Further discussion about UFO source changes will take place on the repository.  The Hack v3.0 update thread is here: 

https://github.com/chrissimpkins/Hack/issues/253

**Comment by burodepeper** [comment]
We can close this issue, right?

**Comment by chrissimpkins** [comment]
yep! whole list complete!
